# Generated by Django 2.1.3 on 2018-11-15 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181115_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 15, 21, 20, 6, 958806)),
        ),
    ]
