# Generated by Django 2.1.3 on 2018-11-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181115_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedroom',
            new_name='bedrooms',
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 15, 23, 31, 56, 697761)),
        ),
    ]
